fandomprojectljh/challenge/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from .views import ChallengeMain,ChallengeOne,ChallengeCompareResult, upload_video

app_name = 'challenge'

urlpatterns = [
    path('',ChallengeMain.as_view(),name='index'),
    path('/<int:pk>',ChallengeOne.as_view(),name='one'),
    path('/<int:pk>/upload', upload_video, name='upload'),
    path('/<int:pk>/challenge_result', ChallengeCompareResult.as_view(), name='compare'),
]
# path('/<int:pk>/upload',upload_video,name='upload1'),

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
# 개발 환경에서만 media 파일을 제공하기 위한 설정

fandomprojectljh/making/urls.py
from django.urls import path
from . import views

app_name = 'making'

urlpatterns = [
    path('', views.index, name='index')
]

fandomprojectljh/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import Main,LogOut

urlpatterns = [
    path('',Main.as_view()),
    path('logout',LogOut.as_view()),
    path('challenge',include('challenge.urls')),
    path('login',include('accounts.urls')),
    path('making',include('making.urls')),
    path('ranking',include('ranking.urls')),
    path("videogallery",include('videogallery.urls')),
    path("admin/", admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

fandomprojectljh/challenge/models.py
from django.db import models
from datetime import datetime

# Create your models here.

## 준오님
# class Video(models.Model):
#     title = models.CharField(max_length=20)
#     video = models.FileField(upload_to="video/%y")

#     def __str__(self):
#         return self.title

class Video(models.Model):
    # title = models.CharField(max_length=100)
    video_file = models.FileField(upload_to='challenge_upload/', default=datetime.now)
    ref_id = models.IntegerField(default=0)

class Ref_Video(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=20)
    singer = models.CharField(max_length=10, default=None)
    video_file = models.FileField(upload_to='ref_video/', default=datetime.now)

fandomprojectljh/challenge/forms.py
from django import forms
from .models import Video

class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('video_file',)

fandomprojectljh/challenge/views.py
from django.db import models
from django.shortcuts import render
from rest_framework.views import APIView
from .forms import VideoForm
from rest_framework.response import Response
from rest_framework import status
from django.views import View
from dance_30 import compare_video
from .models import *
from django.db.models import Max
from .forms import VideoForm


# Create your views here.

# /videogallery 경로 인식 후 index함수가 호출 됨 index함순s html을 렌더링 context포함해서

class ChallengeMain(APIView):
    def get(self,request):
        return render(request, "challenge/challenge.html")
    
class ChallengeOne(APIView):
    def get(self,request, pk):
        challenge = Ref_Video.objects.get(id=pk)
        return render(request,"challenge/ch1.html", {'challenge': challenge})
    
# class ChallegeUpload1(APIView):
#     def get(self,request):
#         return render(request,"challenge/ch1.html")
#     def post(self, request):
#         form = VideoForm(request.POST, request.FILES)
#         if form.is_valid():
#             video = form.save()
#             return Response({'video': video.id}, status=status.HTTP_201_CREATED)
#         else:
#             return Response(form.errors, status=status.HTTP_400_BAD_REQUEST)
        
class ChallengeCompareResult(APIView):
    def get(self, request, pk):
        challenge = Ref_Video.objects.get(id=pk)
        # print("="*100, pk, "="*100)
        
        ref_path = f"./media/{challenge.video_file}"
        # print("="*100, ref_path, "="*100)
        
        latest_video_id = Video.objects.all().aggregate(Max('id'))['id__max']
        video = Video.objects.get(id=latest_video_id)
        # print(video.video_file)
        video_path = f"./media/{video.video_file}"
        print("="*100, video_path, "="*100)
        
        score = compare_video(ref_path, video_path)
        
        context = {
            'score': score,
            'challenge': challenge
        }
        return render(request, "challenge/compare_result.html", context)


######################################

# 동영상 업로드
def upload_video(request, pk):
    challenge = Ref_Video.objects.get(id=pk)
    if request.method == 'POST':
        form = VideoForm(request.POST, request.FILES)
        form.ref_id = pk
        print('='*100, form.ref_id, '='*100)
        
        if form.is_valid():
            video = form.save(commit=False)  # commit=False를 사용하여 객체를 임시로 저장
            video.ref_id = pk  # 동영상 객체에 ref_id 할당
            video.save()  # 동영상 객체를 저장
            context = {
                'form': form,
                'challenge': challenge,  # challenge 객체 추가
            }
            return render(request, "challenge/success.html", context)
    else:
        form = VideoForm()
        form.ref_id = pk
        # print('-'*100, form.ref_id, '-'*100)
        
        context = {
            'form': form,
            'challenge': challenge,  # challenge 객체 추가
        }
    return render(request, 'challenge/upload.html', context)

fandomprojectljh/challenge/templates/challenge/ch1.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'vcss/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vcss/videomain.css' %}">
    <title>Gallery</title>
</head>
<body>
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="header__logo">
                        <a href="/"><img src="/static/img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10 col-md-10">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="/">HOME</a></li>
                                <li><a href="/making">MAKING</a></li>
                                <li><a href="/ranking">RANKING</a></li>
                                <li><a href="/board">BOARD</a></li>
                                <li><a href="/login">LOGIN</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>

    <!-- Discography Section Begin -->
    <section class="discography spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" style="display: flex; justify-content: space-between; align-items: center;">
                    <div style="width: 115px; height: 30px;"></div>
                    <div class="section-title center-title">
                        <h2 style="color: white;">Video Board</h2>
                    </div>
                    <div><button id="upload-button" onclick="window.location.href = '{% url 'challenge:upload' challenge.id %}';">Upload Video</button></div>
                    {% comment %} <a href="{% url 'challenge:one' challenge.id %}"></a> {% endcomment %}
                    
                </div>
                {% comment %} <div id="upload-modal" class="modal">
                    <div class="modal-content">
                      <span class="close">&times;</span>
                      <h2>비디오 업로드</h2>
                      <form id="upload-form" method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        {% comment %} <label for="video-title">제목:</label>
                        <input type="text" id="video-title" required> { endcomment %}
                        
                        <label for="video-file">비디오 파일:</label>
                        <input type="file" id="video-file" accept="video/*" required>
                        <button type="submit">업로드</button>
                      </form>
                    </div>
                  </div> {% endcomment %}
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/20230424_002724.png" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: white;">
                            <span>accuracy</span>
                            <h4>title</h4>
                            <h4>name</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/20230424_002724.png" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: white;">
                            <span>제목 : {{videos.title}}</span>
                            <h4>accuracy</h4>
                            <h4>유저이름 : {{videos.user_id}}</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/20230424_002724.png" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: white;">
                            <span>accuracy</span>
                            <h4>title</h4>
                            <h4>name</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/20230424_002724.png" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: white;">
                            <span>accuracy</span>
                            <h4>title</h4>
                            <h4>name</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/20230424_002724.png" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: white;">
                            <span>accuracy</span>
                            <h4>title</h4>
                            <h4>name</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/20230424_002724.png" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: white;">
                            <span>accuracy</span>
                            <h4>title</h4>
                            <h4>name</h4>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div style="display: flex; justify-content: space-between; align-items: center; width: 100%;">
                    <div style="padding-left: 15px;"><button>Back</button></div>
                    <h2 style="color: white;">Video</h2>
                    <div style="padding-right: 15px;"><button>Next</button></div>
                </div>
            </div>
        </div>
</section>


    {% block content %}
    {% endblock %}
    <script src="{% static 'chjs/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'chjs/bootstrap.min.js' %}"></script>
    <script src="{% static 'chjs/modal.js' %}"></script>
    <script src="{% static 'chjs/main.js' %}"></script>

</body>
</html>

fandomprojectljh/challenge/templates/challenge/ch1upload.html
{% load static %}
{% block extrahead %}
    <!-- Google Font -->
    <!-- Css Styles -->
    <link rel="stylesheet" href="{% static 'mkcss/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'mkcss/rockville.css'%}">
    <link rel="stylesheet" href="{% static 'mkcss/slicknav.min.css'%}">
    <link rel="stylesheet" href="{% static 'mkcss/index.css'%}">
    {% endblock %}
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="header__logo">
                        <a href="/"><img src="/static/img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10 col-md-10">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="/">HOME</a></li>
                                <li><a href="/making">MAKING</a></li>
                                <li><a href="/ranking">RANKING</a></li>
                                <li><a href="/board">BOARD</a></li>
                                <li><a href="/login">LOGIN</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>
    <!-- Main -->
    <div class="wrapper style1">
        <div class="container">
            <div id="root">
                <div class="Contents">
                    <div class="upload-box">
                        <svg viewBox="0 0 2500 400">
                            <symbol id="s-text">
                                <text text-anchor="middle" x="50%" y="80%">Create your Album Art</text>
                            </symbol>
                            <g class = "g-ants">
                                <use xlink:href="#s-text" class="text-copy"></use>
                                <use xlink:href="#s-text" class="text-copy"></use>
                                <use xlink:href="#s-text" class="text-copy"></use>
                                <use xlink:href="#s-text" class="text-copy"></use>
                                <use xlink:href="#s-text" class="text-copy"></use>
                            </g>
                        </svg>
                        <!-- <h2 class="title" style="color:white; margin-bottom:10px;">Create your <em>Album Art</em></h2> -->
                        <hr style="color:whilte;">
                        <div>
                            <input type="text" id="album_name_input" placeholder="앨범 아트 이름 입력">
                        </div>
                        <div id="drop-file" class="drag-file">
                            <img src="/making/static/mkimg/file-earmark-image.svg" alt="업로드 아이콘" class="image">
                            <p class="drag_message">Upload by dragging files</p>
                            <img src="" alt="미리보기" class="preview">
                        </div>
                        <ul style="list-style: none;">
                            <li style="margin:20px 0; text-align:center;">
                                <!-- 파일 업로드 버튼 만들기.  -->
                                <label class="image-upload" for="chooseImage">Choose Image</label>
                                <br>
                                <!-- 파일 업로드 버튼. 사용자 지정파일로 png, jpeg, gif만 기본적으로 업로드 가능하게. -->
                                <!-- 기본적으로 input type="file" 에는 스타일이 적용되지 않기 때문에 input과 label을 같이 써서 label에 이벤트 발생하게 함. -->
                                <input class="file" id="chooseImage" type="file" onchange="dropFile.handleFiles(this.files)" accept="image/png, image/jpeg, image/gif">
                            </li>
                            <li>
                                <input type="submit" id="Request_album" value="Create Album Art">
                            </li>
                        </ul>
    
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer Section End -->

    <!-- Js Plugins -->
    <script src="{% static 'mkjs/jquery-3.3.1.min.js'%}"></script>
    <script src="{% static 'mkjs/bootstrap.min.js'%}"></script>
    <script src="{% static 'mkjs/main.js'%}"></script>
    <script src="{% static 'mkjs/jquery.magnific-popup.min.js'%}"></script>
    <script src="{% static 'mkjs/jquery.nicescroll.min.js'%}"></script>
    <script src="{% static 'mkjs/jquery.countdown.min.js'%}"></script>
    <script src="{% static 'mkjs/jquery.slicknav.js'%}"></script>
    <script src="{% static 'mkjs/DragNdrop.js'%}"></script>

fandomprojectljh/challenge/templates/challenge/challenge.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'chcss/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'chcss/challenge.css' %}">
    <title>Gallery</title>
</head>
<body>
    <div id="preloder">
        <div class="loader"></div>
    </div>
    <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="header__logo">
                        <a href="/"><img src="/static/img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-10 col-md-10">
                    <div class="header__nav">
                        <nav class="header__menu mobile-menu">
                            <ul>
                                <li class="active"><a href="/">HOME</a></li>
                                <li><a href="/making">MAKING</a></li>
                                <li><a href="/ranking">RANKING</a></li>
                                <li><a href="/board">BOARD</a></li>
                                <li><a href="/login">LOGIN</a></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
            <div id="mobile-menu-wrap"></div>
        </div>
    </header>

    <!-- Discography Section Begin -->
    <section class="discography spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-12" style="display: flex; justify-content: space-between; align-items: center;">
                    <div style="width: 115px; height: 30px;"></div>
                    <div class="section-title center-title">
                        <h2 style="color: white;">Challenge</h2>
                    </div>
                    <div style="width: 115px; height: 30px;"></div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/flower2.jpg" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: black;">
                            <span style="color: white;">[Ji Soo - Flower]</span>
                            <h5 style="color: white;">Participants - 24</h5>
                            <h5 style="color: white;">Best User - Jun O Bae</h5>
                            <h5 style="color: white;">Accuracy - 100%</h5>
                        </div>
                        <div>
                            <a href="{% url 'challenge:one' 1 %}" class="entrance_1">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                Challenge Start
                            </a>
                        </div>
                    </div>
                    
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/hypeboy.jpg" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: black; color:white">
                            <span style="color: white;">[New Jeans - Hype Boy]</span>
                            <h5 style="color: white;">Participants - 19</h5>
                            <h5 style="color: white;">Best User - Jun O Bae</h5>
                            <h5 style="color: white;">Accuracy - 95%</h5>
                        </div>
                        <div>
                            <a href="{% url 'challenge:one' 2 %}" class="entrance_1">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                Challenge Start
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6">
                    <div class="discography__item">
                        <div class="discography__item__pic">
                            <img src="/media/queen.jpg" alt="">
                        </div>
                        <div class="discography__item__text" style="background-color: black; color:white">
                            <span style="color: white;">[IDLE - QueenCard]</span>
                            <h5 style="color: white;">Participants - 5</h5>
                            <h5 style="color: white;">Best User - Jun O Bae</h5>
                            <h5 style="color: white;">Accuracy - 98%</h5>
                        </div>
                        <div>
                            <a href="{% url 'challenge:one' 3 %}" class="entrance_1">
                                <span></span>
                                <span></span>
                                <span></span>
                                <span></span>
                                Challenge Start
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
</section>


    {% block content %}
    {% endblock %}
    <script src="{% static 'chjs/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'chjs/bootstrap.min.js' %}"></script>
    <script src="{% static 'chjs/main.js' %}"></script>

</body>
</html>

fandomprojectljh/challenge/templates/challenge/compare_result.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    {% comment %} <a href="{% url 'challenge:compare' challenge.id %}"></a> {% endcomment %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'chcss/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'chcss/challenge.css' %}">
    <title>Result</title>
</head>
<body>
    <h2 style="color: white;">당신의 점수는... {{ score }} 입니다!!</h2>
    <div class="video-container">
        <video controls autoplay>
            <source src="./media/output/c_video_audio_output.mp4" type="video/mp4">
        </video>
    </div>
</body>
</html>

fandomprojectljh/challenge/templates/challenge/success.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Success</title>
</head>
<body>
    <h1>Upload Success</h1>

    <button>
        <a href="{% url 'challenge:compare' challenge.id %}">
        영상비교하기
        </a>
    </button>
    {% comment %} {% if video_url %}
    <video controls>
        <source src="{{ video_url }}" type="video/mp4">
        Your browser does not support the video tag.
    </video>
    {% endif %} {% endcomment %}
</body>
</html>

fandomprojectljh/challenge/templates/challenge/upload.html
<!-- upload.html -->
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  {% comment %} <label for="video-file">비디오 파일:</label>
  <input type="file" id="video-file" accept="video/*" required> {% endcomment %}
  <button type="submit">업로드</button>
</form>

{% comment %} <a href="{% url 'challenge:upload' challenge.id %}"></a> {% endcomment %}